version: "3.8"

services:
  react-app:
    build: .
    ports:
      - "5173:5173"
    container_name: react-app
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - .:/cli-interactive-react-2025
      - /cli-interactive-react-2025/node_modules
